### PR TITLE
Fix overlapping patterns

### LINKED ISSUE #12: Incorrect results when using overlapping patterns
I experience incorrect results when some of the patterns are overlapping in characters. 
~~It only happens when the MatchOnlyWholeWords is option is true.~~ (if set to true combined with matchKind standard, it results in only one match)
I expect the below test to pass.
```
func TestOverlappingPatterns(t *testing.T) {
	trieBuilder := aho_corasick.NewAhoCorasickBuilder(aho_corasick.Opts{
		MatchOnlyWholeWords: true,
		MatchKind: aho_corasick.LeftMostLongestMatch,
		DFA: false,
	})

	patterns := []string{"phonebook", "the phone"}

	trie := trieBuilder.Build(patterns)
	result := trie.FindAll("I'll look into the phonebook")
	if len(result) == 0 {
		t.Error("Did not find match in string")
		t.FailNow()
	}
}
```

### PR DESCRIPTION
**Pull request by semvis123**
Fixes #12
the findIter position was not correctly updated after a match was found.

### CODE REVIEW

**Comment by petar-dambovaliev** [comment]
> Fixes #12 the findIter position was not correctly updated after a match was found.

Hey, thanks for your contribution.
LGTM.

**Comment by semvis123** [comment]
I had marked this as a draft, because I missed a specific case. 
(see https://github.com/trufflesecurity/aho-corasick/pull/1 )
So even though it works better than it did before, this isn't a perfect fix.

**Comment by petar-dambovaliev** [comment]
> 

Do you wanna open another PR to improve it additionally? Otherwise, i can revert this.

**Comment by semvis123** [comment]
Yeah I can do that, once I have a better fix I will open a new pull request.

**Comment by semvis123** [comment]
Seems like the `overlappingIter` is working correctly. It is just not used by the findAll + standardMatch combination.
For more information see:
https://github.com/trufflesecurity/aho-corasick/pull/1

I did however notice that my fix caused the `LeftMostLongestMatch` matchKind to return multiple matches, on overlapping patterns (instead of the left most longest match). I fixed this by reverting this fix for normal matches, and only using this new calculation for matches that are being cancelled due to `MatchOnlyWholeWords`.
I have opened a new pull request for this.

**Pull request merged**
